### ISSUE TITLE
Slack won't issue legacy tokens; how to get a token?

### ISSUE THREAD

**Issue by dmick** [dylex/slack-libpurple#103]
I've been poring through the "app integrations" docs but have yet to find how to just get a Web API token.  Anyone figured it out yet?

**Comment by dylex** [comment]
Does the link from the README no longer work? It is the case that some slacks have administratively prohibited legacy tokens, for which we don't have a solution at the moment.

**Comment by dmick** [comment]
Yes, they won't grant requests for legacy tokens.  It SEEMS like there's a way to get through the new multirole token forest but I haven't found it

**Comment by devinsmith** [comment]
Ripcord manages to get around this by using the browser SSO token imported from a HAR file (I think). Maybe a similar approach can be taken.

**Comment by grimmy** [comment]
See PR #107

**Comment by dylex** [comment]
Closing, since tokens are now actually dead and we have a new password authentication option.
