### ISSUE TITLE
New SSL issue

### ISSUE THREAD

**Issue by zoltan-dulac** [dylex/slack-libpurple#109]
When logging into all the Slack instances I usually join today, I got the following errors 

What follows is a dump of the debug logs (with my info censored).  Are others getting this issue as well?

(11:03:09) util: Writing file prefs.xml to directory /Users/&lt;username&gt;/.purple
(11:03:09) util: Writing file /Users/&lt;username&gt;/.purple/prefs.xml
(11:03:10) account: Connecting to account &lt;account-name&gt;@&lt;instance&gt;.slack.com.
(11:03:10) connection: Connecting. gc = 0x7fe45e5cb570
(11:03:10) slack: api call: https://&lt;instance&gt;.slack.com/api/rtm.connect?token=XXXX&batch_presence_aware=1&presence_sub=true
(11:03:10) util: requesting to fetch a URL
(11:03:10) dnsquery: Performing DNS lookup for &lt;instance&gt;.slack.com
(11:03:10) dns: Wait for DNS child 15514 failed: No child processes
(11:03:10) dns: Created new DNS child 15525, there are now 1 children.
(11:03:10) dns: Successfully sent DNS request to child 15525
(11:03:10) dns: Got response for '&lt;instance&gt;.slack.com'
(11:03:10) dnsquery: IP resolved for &lt;instance&gt;.slack.com
(11:03:10) proxy: Attempting connection to 99.86.61.122
(11:03:10) proxy: Connecting to &lt;instance&gt;.slack.com:443 with no proxy
(11:03:10) proxy: Connection in progress
(11:03:10) proxy: Connecting to &lt;instance&gt;.slack.com:443.
(11:03:10) proxy: Connected to &lt;instance&gt;.slack.com:443.
(11:03:10) gnutls: Starting handshake with &lt;instance&gt;.slack.com
(11:03:10) gnutls: Handshake failed. Error A TLS fatal alert has been received.
(11:03:10) slack: api response: Unable to connect to &lt;instance&gt;.slack.com: SSL Handshake Failed
(11:03:10) connection: Connection error on 0x7fe45e5cb570 (reason: 0 description: Unable to connect to &lt;instance&gt;.slack.com: SSL Handshake Failed)
(11:03:10) account: Disconnecting account &lt;account-name?@&lt;instance&gt;.slack.com (0x7fe45cd685d0)
(11:03:10) connection: Disconnecting connection 0x7fe45e5cb570

**Comment by EionRobb** [comment]
Does it work with NSS instead of gnutls?

**Comment by ehershey** [comment]
I starting getting this today at 8:09am ET. @EionRobb is that a compile time change or configuration somewhere?

**Comment by EionRobb** [comment]
A bit of both, a bit of neither. 
Libpurple will pick up the first ssl plugin it finds in /usr/lib/purple-2 so if you remove/move the ssl-gnutls.so from there it should switch over to nss

**Comment by EionRobb** [comment]
There's also an env var you can turn on to get more verbose gnutls logging when running pidgin from cli with the --debug flag, but I can't remember what that is off the top of my head :)

**Comment by ehershey** [comment]
oh awesome, thanks. I'll try to get more info

**Comment by ehershey** [comment]
I ran this but I think it didn't do the right thing. 
``` sudo mv /usr/local/lib/purple-2/ssl-gnutls.so /usr/local/lib/purple-2/ssl-gnutls.so.bak```

here's a new error snippet. I can play a bit more later or provide more info it would help. 

```
DEBUG slack: api response: Unable to connect to xxx.slack.com: Server requires TLS/SSL, but no TLS/SSL support was found.
```

**Comment by EionRobb** [comment]
Ah ok, in that case, your libpurple package might not have come with ssl-nss.so

**Comment by zoltan-dulac** [comment]
Hey @EionRobb.  Thanks for the quick response! :-)

I'm going to try to use NSS instead of TLS, but there is a bit of a snag.   If you remember, waaaaay back in May 2019, I had an SSL issue with Google Hangouts (see [this thread from the purple-hangouts issue #107 discussion](https://bitbucket.org/EionRobb/purple-hangouts/issues/107/ssl-cert-warning) to refresh your memory.  If you look at the bottom of the page, you'll see that I fixed that issue by turning on TLS and *not* using NSS.  

I'll try turning on NSS and turning off TLS, but I assume I'll get the hangouts issue again, which is not exactly a great solution.  But I guess I will, at least be able to see if it's TLS that's causing the issue.  I'll let you know ... just thought I'd mention this other issue now before I go down that rabbit hole.

**Comment by EionRobb** [comment]
not quite sure what you mean by that, both gnutls and nss are TLS/SSL library plugins

**Comment by dylex** [comment]
I had the same issue today, which went away through some combination of restarting (possibly just picked up a newer gnutls) and adding the [SNI](https://developer.pidgin.im/ticket/17300) patch, if either of those work for anyone.

**Comment by zoltan-dulac** [comment]
> not quite sure what you mean by that, both gnutls and nss are TLS/SSL library plugins

I moved `ssl-gnutls.so` to `ssl-gnutls.so.bak` as you mentioned and restarted pidgin.  When I did this, I didn't get the error anymore and can connect to Slack.

I'll try what @dylex mentioned (i.e. picking up a new gnutls) later today and see if that fixes the gnutls issue.

**Comment by ehershey** [comment]
Rebuilding with no changes other than the SNI patch fixed the problem for me. Thanks everyone!

**Comment by dylex** [comment]
Closing as this seems to be resolved and not directly plugin-related.
