### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by grimmy** [dylex/slack-libpurple#112]
Hiya,

I'm working on trying to get a bunch of the protocol plugins into homebrew for macos and right now slack is blocked because there are no release tarballs.  They aren't necessarily looking for you to do a full release process with a signatures and all that noise, but a simple release tag in git like `v1.0.1` or whatever version  you'd like to pick would allow me to target a known version and not head of master of which they will not accept.

More discussion of the issue can be found in https://github.com/Homebrew/homebrew-core/pull/53557

**Comment by dylex** [comment]
Tagged [0.1](https://github.com/dylex/slack-libpurple/releases/tag/0.1). Does that work?

**Comment by grimmy** [comment]
Yes exactly, thanks!  That said, I'll put a pr in for this in homebrew once my open pr is merged as that should be a bit more useful out of the box.
