### ISSUE TITLE
Login error: invalid_auth

### ISSUE THREAD

**Issue by cptMikky** [dylex/slack-libpurple#113]
Version 0.1, tested using Bitlbee and Pidgin. Slightly different results but neither is willing to authenticate.

Bitlbee:

`account add slack user@example.com@example.slack.com <password>`
results in
```
<@root> slack - Logging in: Requesting RTM
<@root> slack - Login error: invalid_auth
<@root> slack - Logging in: Signing off..
```

Pidgin:
There is no `password` input field in the Account creation dialog:
![pidgin](https://user-images.githubusercontent.com/10010448/81188850-2c672b00-8fb6-11ea-970c-38b79bcba0cb.png)

Pidgin log says
```
(16:06:47) account: Connecting to account user@example.com@example.slack.com.
(16:06:47) connection: Connecting. gc = 0x2783a30
(16:06:47) slack: api_token not set; using password as token
(16:06:47) connection: Connection error on 0x2783a30 (reason: 7 description: API token required)
(16:06:47) account: Disconnecting account user@example.com@example.slack.com (0x1f1fe10)
(16:06:47) connection: Disconnecting connection 0x2783a30
(16:06:47) connection: Destroying connection 0x2783a30
dns[9394]: nobody needs me... =(
```

Out of curiosity I tried putting my password to the API token field:
```
(16:14:25) account: Connecting to account user@example.com@example.slack.com.
(16:14:25) connection: Connecting. gc = 0x2b6c0b0
(16:14:25) slack: api call: https://example.slack.com/api/rtm.connect?token=<password>&batch_presence_aware=1&presence_sub=true
(16:14:25) util: requesting to fetch a URL
(16:14:25) dnsquery: Performing DNS lookup for example.slack.com
(16:14:25) dns: Wait for DNS child 9394 failed: No child processes
(16:14:25) dns: Created new DNS child 13724, there are now 1 children.
(16:14:25) dns: Successfully sent DNS request to child 13724
(16:14:25) dns: Got response for 'example.slack.com'
(16:14:25) dnsquery: IP resolved for example.slack.com
(16:14:25) proxy: Attempting connection to 99.84.221.96
(16:14:25) proxy: Connecting to example.slack.com:443 with no proxy
(16:14:25) proxy: Connection in progress
(16:14:26) nss: SSL version 3.3 using 
<..... snip ......>
(16:14:26) certificate: Successfully verified certificate for example.slack.com
(16:14:26) util: request constructed
(16:14:26) util: Response headers: 'HTTP/1.1 200 OK
< ... snip ...>
(16:14:26) slack: api response: {"ok":false,"error":"invalid_auth"}
(16:14:26) connection: Connection error on 0x2b6c0b0 (reason: 2 description: invalid_auth)
(16:14:26) account: Disconnecting account user@example.com@example.slack.com (0x1f1fe10)
(16:14:26) connection: Disconnecting connection 0x2b6c0b0
dns[13724]: nobody needs me... =(
```

That's very similar to what Bitlbee says so I'm assuming it's the same issue.

It appears to me that the plugin does not even tries to use the password and goes directly for API token.

As luck has it, I've only stumbled upon this plugin today while Slack stopped issuing legacy tokens yesterday...

**Comment by dylex** [comment]
You are correct -- version 0.1 only supports API tokens.  The password authentication was only just added (#107).

**Comment by cptMikky** [comment]
ah, ok. Somehow I was under the impression it was already part of that release. Sorry about the fuzz..

**Comment by dylex** [comment]
Feel free to try master, though. The "release" is a bit arbitrary.

**Comment by cptMikky** [comment]
I'm just about to :) Arbitrary or not, releases are a good thing, especially for distributors and package maintainers.

**Comment by cptMikky** [comment]
Ok, `master` works with Pidgin but still doesn't work with Bitlbee:
```
<@root> username = `user@example.com@example.slack.com'
<@root> password = `********' (hidden)
<@root> slack - Login error: Host setting is required
<@root> slack - Logging in: Signing off..
```

There's no `host` option to set that I could find.

**Comment by dylex** [comment]
I think the host split is `%` not `@` but maybe check with @grimmy who wrote it.

**Comment by cptMikky** [comment]
> I think the host split is `%` not `@` but maybe check with @grimmy who wrote it.

It is, I just re-read the PR again, more thoroughly this time. With `%` as the host split it seems to be working.
