### ISSUE TITLE
Disconnected / Invalid JSON response

### ISSUE THREAD

**Issue by tykeal** [dylex/slack-libpurple#119]
Ever since this morning (2020-09-21) I've been running into issues with being told that Pidgin 'could not process message'. I ended up needing to restart my Pidgin for another reason and now no Slack team that I'm a part of can be connected to. I just get back an almost immediate disconnect with 'Invalid JSON response' as the error.

**Comment by mpmilano** [comment]
Same problem, also occurred within the last hour or so.

**Comment by EionRobb** [comment]
I've got a fix for this, but for some reason my push to github isn't working 
[fix legacy auth.zip](https://github.com/dylex/slack-libpurple/files/5258432/fix.legacy.auth.zip)

The changes are server-side, that they're no longer accepting full URL's, but also that with legacy auth tokens the URL is invalid

**Comment by rynofinn** [comment]
The fix from @EionRobb works for me.  Thank you!

**Comment by EionRobb** [comment]
Sorted out my stuff, and there's a PR at https://github.com/dylex/slack-libpurple/pull/120 :)

**Comment by mpmilano** [comment]
Thanks! fwiw the patch also worked fine for me.  Thanks for the lightning reflexes!
