### ISSUE TITLE
@ commands not working like when connecting via XMPP or when using official Slack client

### ISSUE THREAD

**Issue by zoltan-dulac** [dylex/slack-libpurple#13]
I noticed the other day that `@` commands (like `@here`, or `@username`) doesn't tag at all.  Is this an easy fix?

**Comment by dylex** [comment]
There are two ways we could fix this:

1. Convert `@` commands to the formatted `<@userid>`, `<#channelid>`, and `<!here>` equivalents. This requires looking up user and channel names, so may not be as flexible as what slack does itself.
2. Switch from the current [RTM-based](https://api.slack.com/rtm) message sending mechanism to the [web call](https://api.slack.com/methods/chat.postMessage) so we can use [`link_names=1`](https://api.slack.com/docs/message-formatting) to have slack do it for us.

The problem with the web api is that, as in stands in libpurple, we end up creating an entirely new http connection for each call, which results in a significant amount of overhead and latency, whereas the RTM api is much faster.  I'd prefer to take the first approach, but not sure about the right parsing.

How flexible is slack with `@mentions`? Does it just allow complete usernames/channel names, or do other things work?

**Comment by dylex** [comment]
Oh, also there's [this](https://api.slack.com/changelog/2017-09-the-one-about-usernames) worth considering.

**Comment by zoltan-dulac** [comment]
@dylex That last document you linked to is quite interesting.

Here is what I think (since it sounds like you are asking for my feedback):

1) I would assume that we want to be able to tag people  via `@` commands using whatever is in the list on the right in the channel (question: are these `username`s or `display_name`s?   I *think* they are the `username`s, but I want to clarify).  This doesn't have to be as flexible as how the Slack client does it (IMHO), as long as it is done the same way as one would do when the connect to Slack via XMPP.   I think it would be impossible to do the way that the official slack client can do username to realname lookups, and to me, it isn't important, since I can see the username list on the right and right click to see what each user name is in the real world.

2) I would assume we wouldn't want to use the web api if it's inefficient.

3) Correct me if I'm wrong, but the document seems to imply that you would need to make sure all `@username`s are converted to `id`s before send -- am I right?  I don't know what the most efficient way of doing this lookup would be, but is that information stored by pidgin or the pidgin plugin when the user logs in and as users drop in and out of the channel? (This may seem like a silly question, so I'll admit I am totally ignorant of this).  If not -- I guess there would have to be a routine that looks up this info everytime a user sends a message with an `@`-command.

`@`-mentions work only for usernames, `@here` and `@everyone`, as far as I can tell from this: https://get.slack.help/hc/en-us/articles/202009646-Make-an-announcement .  I would assume we want to implement those too.

I don't know if anything I said helps ... I hope it does.

**Comment by dylex** [comment]
That is helpful and seems generally reassuring as the right idea. Right now the names in the list (and everywhere in the interface in fact) are all usernames, but given slack's "new direction" it seems like I should change them to display names everywhere. The problem with display names is that they have spaces (I think?), so matching `a @display name mention` in text becomes somewhat harder since you don't know when the mention stops. We could strip spaces from display names and make people write `@firstlast` instead of `@first last` but it seems non-intuitive.

Aside from the space problem, I think I have a sense how to implement the rest of this, and could do so with `@username`, `#channelname`, `@here`, and `@everyone` now as a starting point, if that makes sense.

**Comment by dylex** [comment]
One more question -- should these be case sensitive? They seem to be in slack (`@HERE` does not work), but it also auto-corrects them to the correct case. (For now I'll do it case sensitive because it's slightly easier, but can be adjusted later with space-normalization somehow.)

**Comment by dylex** [comment]
See how this works for you. It's pretty strict, but should generally do the right thing.

I also realized we could match on purple's buddy names instead or in addition (though i'm not sure aliasing buddies works right anyway), modulo the space issue. Maybe that would be better...

**Comment by zoltan-dulac** [comment]
1) In my opinion, I think it would be best to start with `@username`.  I agree that the Display Name spacing issue will probably require some thought.  Slack has an auto complete system with them, which (correct me if I'm wrong) would be impossible to implement in the 2.x branch of pidgin (I have never used 3.x).

As for case-sensitivity -- I'd say yes .. for now.

I am trying out the new additions -- looks great so far!  I'll let you know if there are any issues.  Thank you!

**Comment by zoltan-dulac** [comment]
It looks like this works, so If you want to close this, feel free.
