### ISSUE TITLE
Chat rooms's people lists are shown as empty

### ISSUE THREAD

**Issue by pacak** [dylex/slack-libpurple#133]
I can see messages from everyone but list of people are empty:

![1](https://user-images.githubusercontent.com/66211/109103294-93ccb200-7765-11eb-8123-4183662df6c9.png)

Most recent version, not sure how to debug it further.

**Comment by anrxc** [comment]
https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by pacak** [comment]
I'm having the same problem again. Started a day or two ago
