### ISSUE TITLE
Mac OSX build instructions or resources.

### ISSUE THREAD

**Issue by ru5t** [dylex/slack-libpurple#135]
Hi! Thanks for great product!
**Is there anyone currently, who managed to build under OSX?** There's many questions - environment setup, build process. 
Trying to build it and facing difficulties:
### Compiling
* pkg-config can't find purple (for sure, because there's no way to install it for development scope in OSX as I found. Only download adium and use it from there `/Applications/Adium.app/Contents/Frameworks/libpurple.framework/Versions/...`)
* glib - even installed via brew isn't available during make.

Above solved editing CFLAGS:
```
-I../adium/Frameworks/libpurple.framework/Versions/2.12.0r11b8084bcff4/Headers \
    -I/usr/local/Cellar/glib/2.68.0/include/glib-2.0 \
    -I/usr/local/Cellar/glib/2.68.0/lib/glib-2.0/include \
```
### Linking
Can't find way to link against libpurple. Tried to provide -L path to library in app contents. Tried -l to file itself. As I see, it is dylib (from objdump -p). And yet I can't get it to link. 

Built pidgin's libpurple. It is also dylib. Also can't link against it.

### Better way?

**Comment by EionRobb** [comment]
Are you trying to build it for Pidgin on OSX or for Adium?

**Comment by ru5t** [comment]
For adium

**Comment by EionRobb** [comment]
Ah. You'll need to create an Adium plugin that's a wrapper for this libpurple one, as Adium can't load libpurple plugins natively 

eg, see https://github.com/tripplet/skypeweb4adium for inspiration

**Comment by ru5t** [comment]
Ok) so Pidgin then)
### Building
Installed it with brew: `brew install pidgin`
Modified CFLAGS:
```
-I/usr/local/Cellar/pidgin/2.14.1_1/include/libpurple \
    -I/usr/local/Cellar/glib/2.68.0/include/glib-2.0 \
    -I/usr/local/Cellar/glib/2.68.0/lib/glib-2.0/include \
```
No mods for link process.
It compiles and links. I don't really get how does it link though. I didn't provided Makefile with libpurple location.
### Installation
Fails :
```
 make install-user
install -D libslack.so /Users/ru5t/.purple/plugins/libslack.so
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install-user] Error 64
```
Installed via manual copy and it seems to work. Cool. Can be closed
