### ISSUE TITLE
make install-user doesn't quite work

### ISSUE THREAD

**Issue by rrthomas** [dylex/slack-libpurple#136]
When I restarted pidgin after `make install-user`, Slack didn't show in the list of protocols.

When I moved the plugin from `~/.purple/plugins/libslack.so/libslack.so` to `~/.purple/plugins/libslack.so`, it worked fine. (Using Pidgin 2.14.1.)

Thanks for this plugin!

**Comment by rrthomas** [comment]
Thanks!

**Comment by dylex** [comment]
actually that didn't quite work somehow... (install is very fragile across platforms)
