### ISSUE TITLE
Slack settings and commands not working

### ISSUE THREAD

**Issue by vnckppl** [dylex/slack-libpurple#142]
I am using https://github.com/ezkrg/docker-bitlbee-libpurple to run Slack. Using this setup, I am having some issues with a few commands:

I am looking to set the variables `open_chat`, `connect_history`, and `thread_history`, but I can't find them. `set` or `acc <some_account>` set do not show these variables.

Also, the command `\history` does not work for me. It gives the error message `history: Unknown command`.

I posted this issue in the docker-bitlbee-libpurple github (https://github.com/ezkrg/docker-bitlbee-libpurple/issues/21), but was referred back to here. 

Any help is welcome.

**Comment by EionRobb** [comment]
Do you know which version of the slack plugin gets included in the docker image?  The `/history` support was added in a month ago, so it might not be in your image yet?

**Comment by vnckppl** [comment]
Okay this makes sense. I read through the docker file and noticed that indeed a specific version of this plugin was being pulled (i.e., 2e9fa02). I changed it to the latest version as of today (i.e., e0c73ae) and now I do have those options available. Thanks!

**Comment by Barbarossa93** [comment]
How are you able to use the `/history` command with bitlbee? I just get `[bitlbee] history Unknown command`

**Comment by vnckppl** [comment]
> How are you able to use the `/history` command with bitlbee? I just get `[bitlbee] history Unknown command`

I haven't used it as a command, but just the channel flag/option so that when I reopen a channel, I see the history. Does that work for you?

**Comment by Barbarossa93** [comment]
That only seems to work if the channel had unread messages. Ideally I'd like to query the history in channels that didn't have any new messages to get some context .
