### ISSUE TITLE
Example commands usage in bitlbee?

### ISSUE THREAD

**Issue by Barbarossa93** [dylex/slack-libpurple#144]
Sorry to make an issue when this is more a question, but unfortunately I can't seem to use the commands documented in the README with bitlbee. As mentioned in #142, the commands are returned as `[bitlbee] history Unknown command` with the `/history` command as an example. Is there something more to it than just typing `/history 5`? If it helps, I'm connecting to my bouncer which is connected to the local bitlbee instance using irssi as the local client.

**Comment by chex3** [comment]
Hi, I had this issue with using the / commands thru bitlbee a few months ago, and I was told here that it wasn't possible to issue any / commands to the slack plugin from bitlbee, it only works with Pidgin plugin.

**Comment by Barbarossa93** [comment]
Darn, that's unfortunate :(

Thanks for letting me know!

**Comment by Barbarossa93** [comment]
In case other people find themselves here, here's what I ended up doing: In ZNC (the bouncer), I disabled Autoclear buffer and increased the buffer size. So everytime I connect, I get the last w/e number of messages I set it to. It doesn't help in the immediate need, but over time it effectively does what I want it to do.
