### ISSUE TITLE
Can't connect to a renamed channel as chat

### ISSUE THREAD

**Issue by barefootcoder** [dylex/slack-libpurple#147]
Okay, I always connect to the Slack "channels" as if they were chat rooms.  I add a chat, click the "Room List" button, find the channel by name, and Bob's yer uncle.

Now we have a new channel.  I added it as I always do, _and it worked perfectly_.  Except then they renamed the channel.  I noticed that any messages after the rename weren't showing up in my pidgin window, so I figured I just needed to rejoin under the new name.  When I try that, it lets me add the chat just fine.  But, when I try open the window in Pidgin, I get a "method deprecated" error.  I also get that when adding the chat in the first place *iff* I click the "auto-join" checkbox.

Any thoughts?  I also tried joining by name (i.e. not using the Room List), but that doesn't seem to fare any better.

**Comment by barefootcoder** [comment]
FWIW, that annoying dialog keeps popping up.  It definitely isn't stopping me from receiving messages at all, it's just ... annoying. :-/  I've attached an image so you can see exactly what it look like, in case that helps.  Do you have any thoughts on how to make it stop?

![unknown_method](https://user-images.githubusercontent.com/315362/140843524-e94b09df-2f17-4a87-a875-07dd52180023.png)

**Comment by dylex** [comment]
I believe #148 may fix this actually, thanks to @gabor-braun. Sorry it took so long for anyone to notice it.

**Comment by barefootcoder** [comment]
Yep, that appears to have fixed it!  I wanted to give it a few days to make sure, but upgrading to the latest version (as of 11/10) seems to have made the whole thing go away.  So I'm closing out this issue.

Thx for all your help!
