### ISSUE TITLE
how to list channels?  how do join a channel?

### ISSUE THREAD

**Issue by danhimalplanet** [dylex/slack-libpurple#17]
I'm running this with bitlbee-libpurple

How do I list channels?

How do I join a channel?

with a similar plugin, 'bitlbee-discord', i do this:

channel list discord

**Comment by zoltan-dulac** [comment]
@danhimalplanet  This can be done in Pidgin easily via  clicking File > Add Chat.

1) In the "Account" dropdown, choose your slack account
2) Click on "Room List"
3) It will give you a list (in a nice tree structure) of all the channels you can join.

Does this help?

**Comment by dylex** [comment]
Yes, channels are exposed through the standard libpurple room api. It sounds like your question is more about how bitlbee works with libpurple, so you might try asking there.

**Comment by EionRobb** [comment]
On bitlbee it's `chat add slack general`

**Comment by dylex** [comment]
In terms of listing channels, it looks like bitlbee doesn't implement the "expand roomlist category" that this relies on to request subsets of the channels, so can never get the lists (but maybe I've missed something).

I'm thinking about switching to the new slack conversation api which may allow me to avoid this extra expand step, but it would be nice if there were a way in bitlbee to expand a roomlist category to get the actual list.

**Comment by EionRobb** [comment]
tbh, Slack is the first prpl I've seen that uses that "expand roomlist" callback thing :)

Any reason you can't make all the calls without the expand trigger?

**Comment by dylex** [comment]
Mainly just because the slack api has 5 separate calls to return the lists (and aggressive rate limiting so you can't make them all at once) and I was too lazy to coordinate chaining them all, but the new api provides a single call to get them all so that will help.

**Comment by dylex** [comment]
Reopening this to remind myself to switch to `conversations.list` to slightly simplify the room list and maybe only use expand for pagination and archived channels.
