### ISSUE TITLE
Login error: unknown_method

### ISSUE THREAD

**Issue by dshanske** [dylex/slack-libpurple#173]
Updated my plugin to the latest version and started getting a Login error: unknown method error.

**Comment by waptaff** [comment]
I run a version that dates back August 2021 and I also get this `unknown_method`; that started to happen to me on 2022 Dec 15 21:53 UTC.

**Comment by waptaff** [comment]
This seems to happen with password authentication only.

If in the password field, a legacy token is used, login works, as using a token skips over the now-gone `auth.findUser` API call.

Those tokens are long strings that start with `xox` that can be found at https://api.slack.com/legacy/custom-integrations/legacy-tokens but AFAIK unfortunately new ones cannot be created.

As `auth.findUser` is only used to resolve an e-mail address into an internal Slack User ID, perhaps it'd be possible to add a configuration field that stores this along with the username; I don't know if it's doable though, I'm not familiar with PurpleAPI internals.

**Comment by dylex** [comment]
This is unfortunate. It would be a fairly easy change to skip `auth.findUser` and use the username as the userid, but (1) it's not trivial to get a userid out of slack, and (2) I'm worried if they got rid of this they may have changed the whole authentication flow, so `auth.signin` may not work either.  Unfortunately none of my slacks seem to be giving this error (yet), so I don't have a good way of testing this.  If someone else would like to, I've put a hack on the `finduserhack` branch that uses email as userid if it doesn't have a `@` (which userids should not).

I believe this authentication flow was originally extracted from the mobile client.  We could try to figure out what it does now...

**Comment by Thaodan** [comment]
Started to get these a few days earlier too. I tried to find docs around the api call however no other program does use it from what I see.

**Comment by Thaodan** [comment]
> I believe this authentication flow was originally extracted from the mobile client. We could try to figure out what it does now...

https://github.com/dylex/slack-libpurple/pull/162  might help here, it's not as good of a workflow but is a good intermediate thing until we have something else.

**Comment by dchmelik** [comment]
I have same problem on this year's slack-libpurple versions.

**Comment by Fyren** [comment]
> Unfortunately none of my slacks seem to be giving this error (yet), so I don't have a good way of testing this. If someone else would like to, I've put a hack on the `finduserhack` branch that uses email as userid if it doesn't have a `@` (which userids should not).

I tried out the branch and it appears to work for me.

**Comment by xsteadfastx** [comment]
does the branch only work if i have a legacy token? or does the normal password authentication work?

**Comment by Fyren** [comment]
I only tried it with a password.

**Comment by kacf** [comment]
I think the login method doesn't matter, because with that branch you do the login in your browser, and only the tokens are given to libpurple.

**Comment by kacf** [comment]
Ok. My point is that even with a password, you can use the token approach which is described in the pull request, and that method would also work.

**Comment by xsteadfastx** [comment]
ok... right now i just used the branch... didnt reauthenticate or something. still get the unknown method error. so i should delete the account and try to readd it?

**Comment by kacf** [comment]
You have to use the approach described at the top, you can't just input your password.

**Comment by xsteadfastx** [comment]
followed it... so... im using the `finduserhack` branch and the password with the extracted tokens from #162 and get `Invalid JSON response`.

**Comment by xsteadfastx** [comment]
ok... i tried the branch from #162 and it worked fine :)

**Comment by djhaskin987** [comment]
1. Open web client
2. Click on your picture in the upper right corner
3. Select "Profile"
4. Your URL bar should now have this in it: `https://app.slack.com/client/<LONG_WEIRD_STRING>/<OTHER_LONG_WEIRD_STRING>/rimeto_profile/<LAST_LONG_WEIRD_STRING>`
5. Copy `<LAST_LONG_WEIRD_STRING>` from the URL and use it as your username in the pidgin field on the `finduserhack` branch
6. Everything worked :D

**Comment by djhaskin987** [comment]
I should note: I used #162 but when I did, pidgin never listed the people in the room. The feature of listing members of a channel was broken, which is why I switched back to the `finduserhack` branch as in the workaround above.

**Comment by djhaskin987** [comment]
However, when I do this, it prints my replies to people in conversations *twice*, which is annoying.

**Comment by djhaskin987** [comment]
So, @dylex , a suggestion: In the `finduserhack` branch, please make it so that the "Local Account Alias" field is used for identifying messages that come in as the user, instead of the "username" field? Maybe.

**Comment by vanquishedangel** [comment]
I think I found the solution in #177

**Comment by dchmelik** [comment]
Where's 'the finduserhack branch'?

**Comment by vanquishedangel** [comment]
the find user hack is linked below but it is also on the main page for the pluging. Just look for "main" and click it and you get the option for a different branch, however it was confusing to me at first as well.

https://github.com/dylex/slack-libpurple/commit/b0453c713f1c4f53a4ef30bc3b51f541f5c752c0

**Comment by dchmelik** [comment]
> the find user hack is linked below but it is also on the main page for the pluging. Just look for "main" and click it and you get the option for a different branch, however it was confusing to me at first as well. Also if that does not work try the solution I found in

Well, the source code has changed since then.  If it's in the new commit, it doesn't work for me, and if it isn't, I don't know that the line numbers are same so if the hack could still be used.

**Comment by vanquishedangel** [comment]
All good, you asked and I linked is all. You could try the solution it may work for you, just back up the file and save the old one. If it does not work just restore the file. Mine is not working after I used the member ID in place of the user name and used my regular password to log in.

**Comment by gzuaps** [comment]
just confirming that the finduserhack branch worked for a new workspace I was added to.

**Comment by sahal** [comment]
I've updated the [AUR build for this package](https://aur.archlinux.org/packages/slack-libpurple-git) to use this branch as it does seem to work with some workspaces.

Unfortunately, a public slack workspace that doesn't seem to work with this branch is: https://kubernetes.slack.com.   

I'm not sure if this is due to being in too many channels or what.  The json that the debug window shows seems to be cutoff before the following is shown in the debug window:

```
(13:56:30) slack: api response: { . . . 
"real_name_normalized":"<REDACTED>","display_name":"<REDACTED>"
(13:56:30) connection: Connection error on 0x556d372dab50 (reason: 0 description: Invalid JSON response)
```

**Comment by dchmelik** [comment]
I see there have been commits since this--isn't it going to be pulled back into the main branch to fix current versions?  Now the choice is either use the older fix with other bugs, or the newer ones without those but without slack...

**Comment by vanquishedangel** [comment]
> I see there have been commits since this--isn't it going to be pulled back into the main branch to fix current versions? Now the choice is either use the older fix with other bugs, or the newer ones without those but without slack...

I may need some help with the lingo you used, but mine is working great. #177 worked, you need the member ID from your profile to use as your user name, then log in with your normal password.

**Comment by dchmelik** [comment]
> #177 worked, you need the member ID from your profile to use as your user name, then log in with your normal password.

That's for pidgin;; doesn't work for other libpurple software such as bitlbee.

**Comment by tkasci** [comment]
I would greatly appreciate if there was a fix for this plugin that makes it usable with bitlbee again.

**Comment by dylex** [comment]
I've cleaned up, lightly documented, and merged finduserhack since it seems to be working for most people, so I'll close this.

I'm not sure why this wouldn't work for bitlbee.  What problem are you having? Are you sure it's related to this issue?

**Comment by tkasci** [comment]
> I'm not sure why this wouldn't work for bitlbee. What problem are you having? Are you sure it's related to this issue?

I don't know but @dchmelik had this theory. The error persists if I use the Slack user ID that I retrieved from the web app. I also set the lazy_load option to TRUE.

`[19:41] <@root> slack - Login error: unknown_method`

Here is the full output:
```

[19:45] <@tim> account slack on
[19:45] <@root> slack - Logging in: Looking up team
[19:45] <@root> New request: Request: SSL Certificate Verification
[19:45] <@root>
[19:45] <@root> Accept certificate for slack.com?
[19:45] <@root>
[19:45] <@root> The certificate for slack.com could not be validated.
[19:45] <@root>
[19:45] <@root> The certificate is not trusted because no certificate that can verify it is currently
                trusted.
[19:45] <@root> You can use the yes/no commands to accept/reject this request.
[19:45] <@tim> yes
[19:45] <@root> Accepted: Request: SSL Certificate Verification
[19:45] <@root>
[19:45] <@root> Accept certificate for slack.com?
[19:45] <@root>
[19:45] <@root> The certificate for slack.com could not be validated.
[19:45] <@root>
[19:45] <@root> The certificate is not trusted because no certificate that can verify it is currently
                trusted.
[19:45] <@root> slack - Logging in: Finding user
[19:45] <@root> slack - Login error: unknown_method
[19:45] <@root> slack - Logging in: Signing off..
```

**Comment by dylex** [comment]
This was with the finduserhack branch with a username without an `@` in it? Is it possible bitlbee is adding an `@` to the username somehow?

**Comment by tkasci** [comment]
I just pulled the repository again and recompiled it. Now it works. Sorry, I somehow thought the fix was already incorporated long ago…
