### ISSUE TITLE
Slack not connecting in Pidgin

### ISSUE THREAD

**Issue by kujakiller** [dylex/slack-libpurple#176]
Hello, im hoping to get a response from the author dylex or someone from the community ASAP about this issue. Just tonight at around 11:30 PM, March 13 2023 an error message popped up from pidigin saying it would not connect to my slack channel because "SSL peer presented an invalid certficate" and/or "the certficate chain is invalid" or something like that. 

I clicked close and things seemed to be fine, but a couple hours later it popped up, and now it just wont connect at all.
This also happened about a month ago, and somehow after a few hours, it just auto-reconnected just fine until tonight when it started again.

The only thing i could think of that i tried to do already was deleting all the slack related certificates from the certificate manager in pidgin, close and reopen the program cause i thought it would re-create them all, but it didnt help nor create any new certificate files. I backed them all up before so i wouldnt lose them just in case.

I also tried downloading the latest libslack.dll file from the main github page here. and replacing that with the previous old file (backed up first) - close/reopen program but it still didnt help.

I have the info from the debug window what it says about this. I do not know what to do, I hope to get some help reguarding this as I need to get back there. :(

(03:52:59) proxy: Connecting to odysseydevteam.slack.com:443.
(03:52:59) proxy: Connected to odysseydevteam.slack.com:443.
(03:52:59) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(03:52:59) nss: subject=CN=slack.com issuer=CN=R3,O=Let's Encrypt,C=US
(03:52:59) nss: subject=CN=R3,O=Let's Encrypt,C=US issuer=CN=ISRG Root X1,O=Internet Security Research Group,C=US
(03:52:59) nss: subject=CN=ISRG Root X1,O=Internet Security Research Group,C=US issuer=CN=DST Root CA X3,O=Digital Signature Trust Co.
(03:52:59) nss: subject=CN=DST Root CA X3,O=Digital Signature Trust Co. issuer=CN=DST Root CA X3,O=Digital Signature Trust Co.
(03:52:59) certificate/x509/tls_cached: Starting verify for odysseydevteam.slack.com
(03:52:59) certificate/x509/tls_cached: Checking for cached cert...
(03:52:59) certificate/x509/tls_cached: ...Found cached cert
(03:52:59) nss/x509: Loading certificate from C:\Documents and Settings\Mike\Application Data\.purple\certificates\x509\tls_peers\odysseydevteam.slack.com
(03:52:59) certificate/x509/tls_cached: Peer cert did NOT match cached
(03:52:59) nss: CERT 2. CN=ISRG Root X1,O=Internet Security Research Group,C=US [Certificate Authority]:
(03:52:59) nss:   ERROR -8162: SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE
(03:52:59) nss: CERT 3. CN=DST Root CA X3,O=Digital Signature Trust Co. [Certificate Authority]:
(03:52:59) nss:   ERROR -8162: SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE
(03:52:59) certificate: Failed to verify certificate for odysseydevteam.slack.com
(03:52:59) slack: api response: Unable to connect to odysseydevteam.slack.com: SSL peer presented an invalid certificate
(03:52:59) connection: Connection error on 02DEC640 (reason: 0 description: Unable to connect to odysseydevteam.slack.com: SSL peer presented an invalid certificate)

**Comment by ernes32** [comment]
They (slack.com) have changed their root SSL cert to "Let's Encrypt". Just update/add new one in "ca-certs" folder.
https://letsencrypt.org/certificates/

**Comment by kujakiller** [comment]
Ah i see. Thank you very much. I actually had just managed to get it to work yesterday before your reply, after trying more things. I was going to the "application data" directory of where pidgin stores it's settings, and found the certificate folder in one of those paths the "tls cached" and was trying to mess with that putting new certificates there, but with no luck.

Then i tried pidigin's main Program Files folder, at ca-cers like you mentioned. - I opened the site in browser and exported 3 certifcates it was displaying there, and put those in that folder, and it worked. :)
Thank you for the info though, i do appreciate it very much.
