### ISSUE TITLE
Setting host on bitlbee?

### ISSUE THREAD

**Issue by snan** [dylex/slack-libpurple#186]
```
12:51 <sandra> Account 2 on
12:51 <root> slack - Login error: Host setting is required
12:51 <root> slack - Logging in: Signing off..
12:51 <sandra> Account 2 set Host [here is where I put the workspace name]
12:51 <root> Setting `Host' does not exist.
```

I've also tried lowercase `host` and `server`.

When I initially added the account I got this "<root> Warning: Passing a servername/other flags to `account add` is now deprecated. Use `account set` instead."

**Comment by jimdigriz** [comment]
@snan it is appended to the username with a `%` seperator, for example:

`bob@example.com%acme.enterprise.slack.com`

Where 'bob@example.com' is your username, and 'acme.enterprise.slack.com' is your hostname; grap it from the regular slack UI under your account listing.

**Comment by snan** [comment]
Yes! The U123456789#workspace.url.here.slack.com works!
