### ISSUE TITLE
spectrum2 how to?

### ISSUE THREAD

**Issue by p5n** [dylex/slack-libpurple#2]
Pidgin shows API key input field, but how can I use this as spectrum2 transport? Jabber transport registration suppose only username and password

**Comment by dylex** [comment]
I don't know anything about spectrum2, but if it's using libpurple, it will have to be made to call `purple_account_set_string(account, "api_token", TOKEN)`. Libpurple frontends should use the configured account options, in which case it should prompt automatically. (Nothing here is specific to pidgin -- in fact I only use finch.)

It would theoretically be possible to have it get the api token from the password field instead, but I thought this would be too confusing, and ideally if this were a registered slack client, users could enter their real slack password instead of an api key.

**Comment by p5n** [comment]
I was able to worked it around with this hack:
```
diff --git a/slack.c b/slack.c
index 00b428f..9908ba2 100644
--- a/slack.c
+++ b/slack.c
@@ -87,9 +87,13 @@ static void slack_login(PurpleAccount *account) {
        const gchar *token = purple_account_get_string(account, "api_token", NULL);
        if (!token || !*token)
        {
-               purple_connection_error_reason(gc,
-                       PURPLE_CONNECTION_ERROR_INVALID_SETTINGS, "API token required");
-               return;
+               token = purple_account_get_password(account);
+               if (!token || !*token)
+               {
+                       purple_connection_error_reason(gc,
+                               PURPLE_CONNECTION_ERROR_INVALID_SETTINGS, "API token required");
+                       return;
+               }
        }
 
        SlackAccount *sa = g_new0(SlackAccount, 1);
```
Personal messages started working, but I still cannot see channels.

**Comment by dylex** [comment]
Using password for token is a reasonable hack, but I'd rather not do long term.

Do you see channels in pidgin? Channels you've joined should show up automatically in your buddy list, and the roomlist and chat join functionality should work as well.

**Comment by p5n** [comment]
Yes, I see, but finaly it crashed:
```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
0x00007fe84dac7b76 in _int_malloc () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fe84dac7b76 in _int_malloc () at /usr/lib/libc.so.6
#1  0x00007fe84dac96a8 in malloc () at /usr/lib/libc.so.6
#2  0x00007fe850d49e53 in  () at /usr/lib/libdbus-1.so.3
#3  0x00007fe850d49f0b in  () at /usr/lib/libdbus-1.so.3
#4  0x00007fe850d4a049 in  () at /usr/lib/libdbus-1.so.3
#5  0x00007fe850d4a29e in _dbus_type_reader_set_basic () at /usr/lib/libdbus-1.so.3
#6  0x00007fe850d479af in _dbus_header_set_field_basic () at /usr/lib/libdbus-1.so.3
#7  0x00007fe850d4c221 in  () at /usr/lib/libdbus-1.so.3
#8  0x00007fe850d4defd in dbus_message_iter_append_basic () at /usr/lib/libdbus-1.so.3
#9  0x00007fe84e3fe090 in purple_dbus_signal_emit_purple () at /usr/lib/libpurple.so.0
#10 0x00007fe84e3b6747 in purple_signal_emit_vargs () at /usr/lib/libpurple.so.0
#11 0x00007fe84e3b689e in purple_signal_emit () at /usr/lib/libpurple.so.0
#12 0x000000000044322a in  ()
#13 0x0000000000443fa4 in  ()
#14 0x00000000004443aa in  ()
#15 0x00000000004b66d8 in  ()
#16 0x00007fe84e6b0343 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007fe84e6af8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x00007fe84e6afc88 in  () at /usr/lib/libglib-2.0.so.0
#19 0x00007fe84e6affa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#20 0x00007fe84f9743a7 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#21 0x0000000000431e99 in main ()
```
after I did right click -> Join

It was on Archlinux x86_64:
```
$ pacman -Q pidgin libpurple 
pidgin 2.12.0-2
libpurple 2.12.0-2
```

**Comment by dylex** [comment]
Looks like pidgin handles roomlists a bit differently. Made this more robust to fix the crash.

**Comment by p5n** [comment]
It looks like spectrum2 handles roomlist even more differently, so I can not see roomlist in XMPP service discovery, but I was able to join typing room name manually.
Thank you.
