### ISSUE TITLE
Response too long (4194304 bytes limit)

### ISSUE THREAD

**Issue by JustinHop** [dylex/slack-libpurple#25]
Upon connection I get an error visible in pidgin

"
Error reading from slack.com: response too long (4194304 bytes limit)
"

Its a corporate slack account with a whole lot of users, many thousands. I can help with debugging, I was not able to find where that limit is set in the code. Sounds like it could be a pidgin issue, but I'm not sure.

**Comment by JustinHop** [comment]
I found it in pidgin
libpurple/util.c

/* 512KiB Default value for maximum HTTP download size (when the client hasn't
   specified a length) */
#define DEFAULT_MAX_HTTP_DOWNLOAD (512 * 1024)

#define MAX_HTTP_CHUNK_SIZE (10 * 1024 * 1024)

**Comment by JustinHop** [comment]
(17:17:07) slack: RTM 1: {"type": "hello"}
(17:17:07) slack: api call: https://slack.com/api/users.list?token=REMOVED&presence=false
(17:17:07) util: requesting to fetch a URL
(17:17:07) dnsquery: Performing DNS lookup for slack.com
(17:17:07) dns: Successfully sent DNS request to child 21341
(17:17:07) dns: Got response for 'slack.com'
(17:17:07) dnsquery: IP resolved for slack.com
(17:17:07) proxy: Attempting connection to 13.33.42.34
(17:17:07) proxy: Connecting to slack.com:443 with no proxy
(17:17:07) proxy: Connection in progress
(17:17:07) proxy: Connecting to slack.com:443.
(17:17:07) proxy: Connected to slack.com:443.
(17:17:08) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(17:17:08) nss: subject=CN=*.slack.com,O="Slack Technologies, Inc.",L=San Francisco,ST=California,C=US issuer=CN=GeoTrust SSL CA - G3,O=GeoTrust Inc.,C=US
(17:17:08) nss: subject=CN=GeoTrust SSL CA - G3,O=GeoTrust Inc.,C=US issuer=CN=GeoTrust Global CA,O=GeoTrust Inc.,C=US
(17:17:08) nss: partial certificate chain
(17:17:08) certificate/x509/tls_cached: Starting verify for slack.com
(17:17:08) certificate/x509/tls_cached: Checking for cached cert...
(17:17:08) certificate/x509/tls_cached: ...Found cached cert
(17:17:08) nss/x509: Loading certificate from /home/justin/.purple/certificates/x509/tls_peers/slack.com
(17:17:08) certificate/x509/tls_cached: Peer cert matched cached
(17:17:08) nss/x509: Exporting certificate to /home/justin/.purple/certificates/x509/tls_peers/slack.com
(17:17:08) util: Writing file /home/justin/.purple/certificates/x509/tls_peers/slack.com
(17:17:08) nss: Trusting CN=*.slack.com,O="Slack Technologies, Inc.",L=San Francisco,ST=California,C=US
(17:17:08) certificate: Successfully verified certificate for slack.com
(17:17:08) util: request constructed
(17:17:09) util: Response headers: 'HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Sat, 10 Feb 2018 01:17:08 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Accepted-OAuth-Scopes: users:read,read
X-Content-Type-Options: nosniff
X-OAuth-Scopes: read,client,identify,post,apps
X-Slack-Backend: h
X-Slack-Req-Id: REMOVED
X-XSS-Protection: 0
X-Cache: Miss from cloudfront
Via: 1.1 d954ca31a2d0aa03f205fa0521d17fae.cloudfront.net (CloudFront)
X-Amz-Cf-Id: REMOVED

'
(17:17:11) slack: api response: Error reading from slack.com: response too long (4194304 bytes limit)
(17:17:11) connection: Connection error on 0x5648ece80f80 (reason: 0 description: Error reading from slack.com: response too long (4194304 bytes limit))
(17:17:11) account: Disconnecting account REMOVED (0x5648ec9c86b0)
(17:17:11) connection: Disconnecting connection 0x5648ece80f80
(17:17:11) websocket: removing input 0
(17:17:11) connection: Destroying connection 0x5648ece80f80

**Comment by JustinHop** [comment]
According to https://api.slack.com/methods/users.list it looks like the request needs to be requested using pagination.

**Comment by dylex** [comment]
It shouldn't be too hard to add pagination to these calls. I presume there are a large number of channels as well? I wonder how well pidgin will deal with loading them all into the blist as we do now, but it's worth trying. I'll see.

How many users do we think 4MB is? I guess they recommend 200 so we can start with that.

**Comment by JustinHop** [comment]
Yes, it is for a large organization. Many, many channels. Thanks for the help

**Comment by dylex** [comment]
See if that works for you.  It now does pagination with a limit of 100 for most of these lists, and I've tested with about 250 users. Not sure how this will scale to 10k+ -- there may be other issues.

**Comment by JustinHop** [comment]
It looked like it was working, then I got ratelimited. Thanks a bunch for your help! Here is the debug output after it successfully looped through getting user info.

(23:39:30) slack: api call: https://slack.com/api/users.list?token=REMOVED&presence=false&limit=100&cursor=dXNlcjpVMDQ5QzNFRTE%3D
(23:39:30) util: requesting to fetch a URL
(23:39:30) dnsquery: Performing DNS lookup for slack.com
(23:39:30) dns: Successfully sent DNS request to child 22416
(23:39:30) dns: Got response for 'slack.com'
(23:39:30) dnsquery: IP resolved for slack.com
(23:39:30) proxy: Attempting connection to 13.33.224.10
(23:39:30) proxy: Connecting to slack.com:443 with no proxy
(23:39:30) proxy: Connection in progress
(23:39:30) proxy: Connecting to slack.com:443.
(23:39:30) proxy: Connected to slack.com:443.
(23:39:30) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
(23:39:30) nss: subject=CN=slack.com,O="Slack Technologies, Inc.",L=San Francisco,ST=CA,C=US issuer=CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
(23:39:30) nss: subject=CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US issuer=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(23:39:30) nss: subject=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(23:39:30) certificate/x509/tls_cached: Starting verify for slack.com
(23:39:30) certificate/x509/tls_cached: Checking for cached cert...
(23:39:30) certificate/x509/tls_cached: ...Found cached cert
(23:39:30) nss/x509: Loading certificate from /home/justin/.purple/certificates/x509/tls_peers/slack.com
(23:39:30) certificate/x509/tls_cached: Peer cert matched cached
(23:39:30) nss/x509: Exporting certificate to /home/justin/.purple/certificates/x509/tls_peers/slack.com
(23:39:30) util: Writing file /home/justin/.purple/certificates/x509/tls_peers/slack.com
(23:39:30) nss: Trusting CN=slack.com,O="Slack Technologies, Inc.",L=San Francisco,ST=CA,C=US
(23:39:30) certificate: Successfully verified certificate for slack.com
(23:39:30) util: request constructed
(23:39:30) util: Response headers: 'HTTP/1.1 429 Too Many Requests
Content-Type: application/json; charset=utf-8
Content-Length: 34
Connection: close
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Tue, 20 Feb 2018 07:39:30 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer
Retry-After: 7
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-OAuth-Scopes: read,client,identify,post,apps
X-Slack-Backend: h
X-Slack-Req-Id: 4f04a68f-4967-4fbc-92ca-468dec095bb4
X-XSS-Protection: 0
X-Cache: Error from cloudfront
Via: 1.1 6ed623541a1487ecd1bc71b49417e87c.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 9bQmr5sX9mbCCiJ8ySBHhncjpDCa8UWzkte5bnC-4yl8kFyEatGHdA==

'
(23:39:30) util: parsed 34
(23:39:30) slack: api response: {"ok":false,"error":"ratelimited"}
(23:39:30) connection: Connection error on 0x5616fdb0e940 (reason: 0 description: ratelimited)
(23:39:30) account: Disconnecting account justin.hoppensteadt@slack.com (0x5616fb8499e0)
(23:39:30) connection: Disconnecting connection 0x5616fdb0e940
(23:39:30) websocket: removing input 0
