### ISSUE TITLE
no more "push notifications" after suspend

### ISSUE THREAD

**Issue by t-animal** [dylex/slack-libpurple#26]
When I suspend my machine and it comes back up, I have to manually enter a chat to see the messages there. It does no longer pop up by itself when there are new messages in the chat. When I disable the account and re-enable it, the correct behaviour is restored.

**Comment by dylex** [comment]
I presume you didn't get any errors on resume about "RTM connection closed"? Once you have a chat open, do new message not show up either (even without alerts)? It sounds like the RTM websocket connection closed, but in that case it should disconnect the account. I suppose we could try more actively detecting this by sending pings every so often. This might not be too hard. The result will still be a disconnected account at this point, though, but libpurple should automatically reconnect at that point.

**Comment by t-animal** [comment]
Mhm, I do not observe this problem any more. Maybe it was fixed by accident or I misdiagnosed it. Closing.
