### ISSUE TITLE
Members not loaded for conversations

### ISSUE THREAD

**Issue by kendrak24** [dylex/slack-libpurple#32]
Currently, all channels have an empty list of members. The conversations api seems to not have quite stabilized yet, but according to the doc, the conversations.info does not return members (besides num_members). There is however a conversations.members api method that seems specifically intended for this. 

[Conversations.info API](https://api.slack.com/methods/conversations.info)
[Conversations.members API](https://api.slack.com/methods/conversations.members)

**Comment by dylex** [comment]
Switched this back to old api, at least for now.

**Comment by dylex** [comment]
(Assuming this is about the member list that comes up when you open a conversation. if not, please reopen.)

**Comment by kendrak24** [comment]
Works fine now.

> Seems strictly worse to have to make a separate call for members.
It's probably because the number of channel members can be many, and they wan't to have that in a separate call so it can be paginated.
