### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by FuzzJunket** [dylex/slack-libpurple#36]
I don't know how much detail or debug info I can provide, but there might be an issue with the plugin on ARM processors. I have a SheevaPlug with an ARM9 processor on which I compiled the slack-libpurple plugin. When I logged in using Finch, it connected successfully but constantly disconnected and reconnected, making it practically unusable. I then tried the same thing on my desktop running an AMD x86-64 processor and it worked perfectly.

Both computers were running Debian Stretch and were on the same Internet connection, so as many variables as possible were the same. I'd been running Finch on the SheevaPlug successfully for ages with other types of account, so it doesn't seem to be a Finch problem. My best guess is that slack-libpurple makes some assumptions or does something that causes it to bork on the wrong processors.

Please let me know if there's any way I can give you debug info, but right now I'm not sure if/where any of this stuff gets logged.

**Comment by dylex** [comment]
Pardon my ignorance but mainly so I know what to look for -- it looks like ARM9 is 32-bit and probably little-endian, is that right?  There are some 64-bit things that got tweaked in a recent win32 changed that are worth checking.  Just to be sure, I presume you're on the latest master rev -- there was a recent short-lived bug (#31) that caused this problem.

**Comment by FuzzJunket** [comment]
I had to do some digging, but it looks like ARM9 is 32-bit and can support either endian-ness. I was using Debian's armel build, which is specifically little-endian. I was also using the latest master (as of the 15th of March). I had the same thought and made sure I did a fresh check-out and build, but unfortunately the problem persisted.

**Comment by dylex** [comment]
Okay, well I'm not seeing anything else obvious in that case, so if you're willing, debug messages might help.  There's a debug option in the window menu on finch, but the easiest way to capture them is to run it as `finch -d 2> debug.log`.  The file will be pretty big and contain lots of sensitive info, so feel free to censor the tokens and messages and/or email it to me.

**Comment by dylex** [comment]
It looks like it might be failing while sending websocket messages, possibly due to unaligned memory access.  I've fixed this access, though I would've thought it would crash immediately if that were the problem.  Regardless, could you try again?

**Comment by FuzzJunket** [comment]
Oh my god, it works! You're a genius. I've been logged in for about 15 minutes without being disconnected and reconnected.

Thanks for fixing this so quickly. I don't think there's anything we need to follow up on, so I'll go ahead and close this ticket.
