### ISSUE TITLE
add support for threading

### ISSUE THREAD

**Issue by tychoish** [dylex/slack-libpurple#37]
this could easily just "unthread" rather than swallowing messages.

**Comment by dylex** [comment]
I see threaded messages, at least in finch, whether they're sent just to the thread or to both.  They do come with some blank messages (generated by the attachment  to the original message, which we don't process) and with an [edit] when it's sent to both. So perhaps the display could be nicer, but at least they show up.

**Comment by tychoish** [comment]
I agree I think this works fine now.
