### ISSUE TITLE
hang on joining a particular channel

### ISSUE THREAD

**Issue by brianjmurrell** [dylex/slack-libpurple#39]
When I join a particular channel pidgin hangs.  Here is a [debug log](https://github.com/dylex/slack-libpurple/files/1823038/debug.out01.txt) and a [stacktrace](https://github.com/dylex/slack-libpurple/files/1823043/ThreadStacktrace.txt) when it happens.

**Comment by dylex** [comment]
All of those mark calls are very suspicious. It might mean we're making one call per message when replaying history, which shouldn't be happening, and then slack's aggressive throttling ends up sticking somewhere when they stop responding.  Regardless, nothing should be able to hang the pidgin interface completely, just maybe make the protocol stop working. I'll look into the mark calls first.

**Comment by dylex** [comment]
Try with this commit. It's a pretty significant change but should eliminate all those spammy mark calls.

It looks like the channel in question has a huge number of unread messages. Is that right? Do you see these messages before it hangs?

**Comment by brianjmurrell** [comment]
> It looks like the channel in question has a huge number of unread messages. Is that right?

Yeah.  I have not joined that channel in a while.

> Do you see these messages before it hangs?

No, so it hangs every time and I have to kill pidgin.  Rinse, repeat.

I'll try the commit in a bit...

As an aside, is there any way to re-load a plugin while pidgin runs or is stop/start the only way?  I know that you if you install a new plugin and then open the plugs tool (ctrl-u) it will load any not-yet-loaded plugins, so one can install a new plugin without restart.

**Comment by brianjmurrell** [comment]
8b9b990 does seem to resolve the issue of hanging on trying to join a channel with a huge number of unread messages.

**Comment by dylex** [comment]
While you can load and unload normal plugins, but I don't think you can unload a protocol protocol, or at least I've never seen a way. Even if you could, you'd have to disconnect any accounts with it first.

Closing this since it sounds like it's fixed, but feel free to reopen if not.
