### ISSUE TITLE
Can't join group chat

### ISSUE THREAD

**Issue by kurnevsky** [dylex/slack-libpurple#4]
Every time I try to open chat it tells me "Could not join channel, no_channel"

In logs I see request:
```
(12:10:56) slack: api call: https://slack.com/api/channels.join?token={...}&name=%03
(12:10:56) util: requesting to fetch a URL
```
and response:
```
(12:04:57) util: parsed 33
(12:04:57) slack: api response: {"ok":false,"error":"no_channel"}
```
Right after that pidgin falls with segfault.

**Comment by dylex** [comment]
How are you trying to join the chat exactly?

**Comment by kurnevsky** [comment]
Double click on chat from roster.

**Comment by dylex** [comment]
Another victim of testing with finch instead of pidgin: pidgin seems to have an explicit memory leak where it sometimes frees the chat name, but finch never does. Ah, well. Hopefully this should at least work now in both, despite the leak.

**Comment by kurnevsky** [comment]
Yeah, it works now, thanks.
