### ISSUE TITLE
Adium support

### ISSUE THREAD

**Issue by kolsys** [dylex/slack-libpurple#47]
Do you have any plan to add Adium support?

**Comment by dylex** [comment]
As I understand it, Adium just uses libpurple so there's no reason it shouldn't work as is. If it doesn't for some reason I'd certainly consider fixing it if practical or accept a PR to that effect, but I have no way to run Adium myself.

**Comment by dylex** [comment]
It should be in the account settings somewhere, maybe under an advanced or options tab.

If it's really not there, at some point someone proposed using the password as the token is the token isn't set. I still feel that's confusing, but can add it if you have a password field and no api token.

**Comment by dylex** [comment]
Since this has come up before with other protocols, I've changed it to be able to use password as the token.

**Comment by dylex** [comment]
Upon further inquiry, it sounds like Adium actually requires a different kind of plugin, for which an additional wrapper would need to be built for this to work.  I doubt I will be able to provide such a thing myself at this point, but someone else may be up to it, and I'm happy to provide support as I can.  (See https://github.com/tripplet/skypeweb4adium for reference.)

**Comment by EionRobb** [comment]
If you ask @tripplet nicely, he might oblige

**Comment by EionRobb** [comment]
@victori is your code online anywhere? I can offer a few pointers if you'd like

**Comment by victori** [comment]
whoa quick response, did not expect that. I don't have the code online yet since I just started on this project last night and had some mild "success."  Will update this ticket once I place it on my GitHub later this weekend. Also, thank you for any pointers which you can give. The discontinuing of XMPP and IRC gateways is quite disappointing from Slack.

**Comment by victori** [comment]
I haven't had time to work on it this weekend but here is my work so far: https://github.com/victori/slack4adium

**Comment by xypd** [comment]
Thanks for putting the code out there. Hopefully someone might be able to help it progress.

**Comment by victori** [comment]
Well, thanks to Eion's suggestions the Adium plugin is now working with slack! I will do a release later tonight so you don't need to mess with compiling it. The password field is used for the API token.

**Comment by xypd** [comment]
This is awesome news! Thanks for you work @victori. Now no need to do wee-chat or at least rush to set it up.

**Comment by xypd** [comment]
So of course I wanted to try to build it. But got a build fail. So I can wait for your build, but this is what I got. Maybe this is helpful.

`cp: slack-libpurple/img/slack16.png: No such file or directory

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script build/slack4adium.build/Release/slack4adium.build/Script-CD7B08E61B5DAB9000E6E652.sh
(1 failure)
make: *** [compile] Error 65`

**Comment by victori** [comment]
The build is already there under releases.

**Comment by Eingang** [comment]
What kind of token is it? Legacy token? Application OAUTH token? Something else somewhere else in Slack?

Most of the workspaces I belong to don't seem to allow any kind of tokens to be created. )-:

**Comment by dylex** [comment]
It's a legacy token. See the [readme](https://github.com/dylex/slack-libpurple#readme).

**Comment by dylex** [comment]
Since this now exists as separate repo, I'm closing this issue.
