### ISSUE TITLE
Will not compile anymore under RHEL 6 / CentOS 6

### ISSUE THREAD

**Issue by waptaff** [dylex/slack-libpurple#52]
Hi.  Commit d31976bc broke compatibility with at least RHEL6/CentOS6 by using the `g_queue_free_full` function that unfortunately is not part of the glib bundled version (2.28.8) on those operating systems.  From what I understand `g_queue_free_full` is only [syntactic sugar to replace two lines of code with one](https://bugzilla.gnome.org/show_bug.cgi?id=657433).

Would it be possible to replace that call to ensure maximum compatibility?

Thanks!

**Comment by dylex** [comment]
No problem.  (And a reminder to myself to add some CI...)

**Comment by waptaff** [comment]
Wow that was quick, thank you very much, compiles flawlessly now!

**Comment by EionRobb** [comment]
It also broke the windows build, which is building fine now :)
