### ISSUE TITLE
dll for windows?

### ISSUE THREAD

**Issue by ss-17** [dylex/slack-libpurple#53]
Hi.

Is there any ready to use windows build available for download?

Thanks.

**Comment by dylex** [comment]
Not as such. EionRobb contributed some patches for windows compatibility, but I have not tried myself and am not sure what's involved.  If someone does produce one I'll certainly link to it.

**Comment by EionRobb** [comment]
I keep windows builds at https://eion.robbmob.com/libslack.dll

**Comment by dylex** [comment]
Awesome. Link added.
