### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by realies** [dylex/slack-libpurple#54]
Would be great if there is periodical tags in the repository that are considered `stable` and available in the `releases` section.

**Comment by dylex** [comment]
Indeed -- I'm not sure I'd consider anything near stable, yet -- lots of outstanding issues I haven't gotten to. Once I get autoconf and CI going, though, I'll try to pin things down.

**Comment by ktdreyer** [comment]
In the meantime I'm packaging Git snapshots for Fedora and EPEL at https://copr.fedorainfracloud.org/coprs/ktdreyer/purple-slack/ . Thanks a lot for this plugin!

**Comment by HumanG33k** [comment]
Some news about make a release, at least in order to be notify by github. But also in order to facilitate the debian packaging.

**Comment by dylex** [comment]
We now have two release tags and will try to continue tagging going forward.
