### ISSUE TITLE
Outgoing private messages sent from slack app show up in wrong channel?

### ISSUE THREAD

**Issue by mtfurlan** [dylex/slack-libpurple#60]
So I'm pretty sure this isn't user error, but I am using bitlbee-libpurple, and I'm new to bitlbee.

Using the slack client, if I send a private message, I get two new channels in my irc client, a private message with my username on slack, and a private message with the target of the private message.
If I respond in the channel with the target of the PM, it works fine, and if I respond to my slack username, it shows up in the private message to you channel you have in slack.

If I'm in a channel, and I send a message on slack, it does not show up in the channel in my irc client, but if I send a message in the irc client it shows up fine.

So is this a problem with bitlbee-libpurple, slack-libpurple, or something between chair and keyboard?

**Comment by dylex** [comment]
I would assume it's some problem in the interaction between slack-libpurple and bitlbee-libpurple, perhaps around how it's generating outgoing or notification messages, or parsing the conversation name or something. Does the sent message appear in both channels? Do subsequent sent messages appear in both? What about responses from the other user? We recently changed the "remote send" handling in #55 -- maybe this is causing it? What exact version of libpurple?

**Comment by mtfurlan** [comment]
```
versions from debian repos
		bitlbee-libpurple 3.5.1-1
		libpurple-bin     2.12.0-1
		libpurple-dev     2.12.0-1
		libpurple0        2.12.0-1
built locally
		slack-libpurple   0179b2c, current master
```

So for clarity I've renamed my irc user `irc_client`
My slack username is `mark`

I removed the websocket debug and user typing messages from the following logs
As well as these which should be unrelated
```
DEBUG slack: Unhandled RTM type im_marked
DEBUG slack: Unhandled RTM type desktop_notification
```

Send "Ping" to slackbot from lack client, two PMs appear in my irc client:
```
14:23 -!- Irssi: Starting query in localhost with mark
14:23 <irc_client> Ping
14:23 -!- mark [mark@tome]
14:23 -!-  ircname  : mark
14:23 -!-  server   : mark. [slack network]
14:23 -!-           : active
14:23 -!- End of WHOIS
```

```
14:23 -!- Irssi: Starting query in localhost with slackbot
14:23 <slackbot> I searched for that on our Help Center. Perhaps these articles will help:
14:23 <slackbot> • Manage members with SCIM provisioning
14:23 <slackbot> • Mention a member
14:23 <slackbot> • Make an announcement
```

```
DEBUG slack: RTM 1: {"type":"message","channel":"D1X04PSRZ","user":"U1X1S0GTF","text":"Ping","ts":"1526062985.000735","source_team":"T0SU54BNG","team":"T0SU54BNG"}
DEBUG slack: RTM 1: {"type":"im_marked","channel":"D1X04PSRZ","ts":"1526062985.000735","dm_count":0,"unread_count_display":0,"num_mentions_display":0,"mention_count_display":0,"event_ts":"1526062987.000069"}
DEBUG slack: RTM 1: {"type":"message","user":"USLACKBOT","text":"I searched for that on our Help Center. Perhaps these articles will help: \n\u2022 <https:\/\/get.slack.help\/hc\/en-us\/articles\/212572638-manage-members-with-scim-provisioning?sid=zd-af-t0su54bng-u1x1s0gtf|Manage members with SCIM provisioning>\n\u2022 <https:\/\/get.slack.help\/hc\/en-us\/articles\/205240127-mention-a-member?sid=zd-af-t0su54bng-u1x1s0gtf|Mention a member>\n\u2022 <https:\/\/get.slack.help\/hc\/en-us\/articles\/202009646-make-an-announcement?sid=zd-af-t0su54bng-u1x1s0gtf|Make an announcement>","team":"T0SU54BNG","source_team":"T0SU54BNG","user_team":"T0SU54BNG","user_profile":{"avatar_hash":"sv1444671949","image_72":"https:\/\/a.slack-edge.com\/0180\/img\/slackbot_72.png","first_name":"slackbot","real_name":"slackbot","display_name":"slackbot","team":"T0SU54BNG","name":"slackbot","is_restricted":false,"is_ultra_restricted":false},"channel":"D1X04PSRZ","event_ts":"1526062988.000223","ts":"1526062988.000223"}
```

Respond "pong" in irc in the query window to slackbot
Shows up as a PM to slackbot in the slack client.

```
14:26 <irc_client> pong
14:26 -!- slackbot is away: away
14:26 <slackbot> I'm sorry, I don't understand! Sometimes I have an easier time with a few
                 simple keywords.
14:26 <slackbot>
14:26 <slackbot> Or you can head to our wonderful Help Center for more assistance!
```


```
DEBUG slack: RTM: {"id":2,"type":"message","channel":"D1X04PSRZ","text":"pong"}
DEBUG slack: RTM 1: {"ok":true,"reply_to":2,"ts":"1526063166.000274","text":"pong"}
DEBUG slack: RTM 1: {"type":"message","user":"USLACKBOT","text":"I'm sorry, I don't understand! Sometimes I have an easier time with a few simple keywords. \n\nOr you can head to our wonderful <https:\/\/get.slack.help\/hc\/en-us?sid=zd-af-t0su54bng-u1x1s0gtf|Help Center> for more
assistance! ","team":"T0SU54BNG","source_team":"T0SU54BNG","user_team":"T0SU54BNG","user_profile":{"avatar_hash":"sv1444671949","image_72":"https:\/\/a.slack-edge.com\/0180\/img\/slackbot_72.png","first_name":"slackbot","real_name":"slackbot","display_name":"slackbot","team":"T0SU54BNG","name":"slackbot","is_restricted":false,"is_ultra_restricted":false},"channel":"D1X04PSRZ","event_ts":"1526063167.000130","ts":"1526063167.000130"}
```


Respond pong in irc query window to myself in slack
Shows up as a PM to myself in the slack client.
```
14:26 <irc_client> pong
```

```
^[DEBUG slack: RTM: {"id":3,"type":"message","channel":"D1X1SFY79","text":"pong"}
DEBUG slack: RTM 1: {"ok":true,"reply_to":3,"ts":"1526063204.000512","text":"pong"}
```

Then a PM to me in slack:
```
DEBUG slack: RTM 1: {"type":"message","channel":"D1X1SFY79","user":"U1X1S0GTF","text":"Ping?","ts":"1526063609.000731","source_team":"T0SU54BNG","team":"T0SU54BNG"}
```


What I see is that the channel ID for all of the messages that seem like they should be a PM to slackbot have the same ID, and the messages that should be a PM to me have the same ID.
Same thing happens with other PMs. Channels seem to work fine, but I haven't done too much testing.

So I think the next step is to start logging with each message what slack-libpurple thinks the channel is, and when that is correct, start logging it in bitlbee?

Not sure when I'll have time to look into this, but I'll keep working at it when I do get time. Or explain how I did my setup if someone else is motivated, because bitlbee is weird to get started with.

**Comment by mtfurlan** [comment]
It is the former.
I will start looking into bitlbee-libpurple then.
Thank you.

**Comment by mtfurlan** [comment]
I'm switching to weechat as it has built in slack support, so I won't be following up on this, sorry.
Sounds like it's probably an issue with bitlbee-libpurple anyway?
