### ISSUE TITLE
Can't compile on Ubuntu 16.04/17.10

### ISSUE THREAD

**Issue by minibiti** [dylex/slack-libpurple#61]
Hi,

I cloned the project and ran "make install" but I get errors.
I do have libpurple installed:
$ dpkg -l | grep purple
ii  libpurple-bin                              1:2.12.0-1ubuntu2                           all          multi-protocol instant messaging library - extra utilities
ii  libpurple0                                 1:2.12.0-1ubuntu2                           amd64        multi-protocol instant messaging library

But I get these:
$ make install
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Makefile:117: Makefile.dep: No such file or directory
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
gcc -MM -g -O2 -Wall -Werror -Wno-error=strict-aliasing -fPIC -D_DEFAULT_SOURCE=1 -std=c99  slack.c slack-cmd.c slack-message.c slack-conversation.c slack-channel.c slack-im.c slack-user.c slack-rtm.c slack-blist.c slack-api.c slack-object.c slack-json.c purple-websocket.c json.c > Makefile.dep
slack-message.c:388:25: error: missing binary operator before token "("
 #if PURPLE_VERSION_CHECK(2,12,0)
                         ^
Makefile:115: recipe for target 'Makefile.dep' failed
make: *** [Makefile.dep] Error 1

And then if I remove the line with the PURPLE_CHECK_VERSION from the file and force the right value in the If/Else, I get these:
$ make install
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
gcc -MM -g -O2 -Wall -Werror -Wno-error=strict-aliasing -fPIC -D_DEFAULT_SOURCE=1 -std=c99  slack.c slack-cmd.c slack-message.c slack-conversation.c slack-channel.c slack-im.c slack-user.c slack-rtm.c slack-blist.c slack-api.c slack-object.c slack-json.c purple-websocket.c json.c > Makefile.dep
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
gcc -c -g -O2 -Wall -Werror -Wno-error=strict-aliasing -fPIC -D_DEFAULT_SOURCE=1 -std=c99  -o slack.o slack.c
slack.c:7:10: fatal error: accountopt.h: No such file or directory
 #include <accountopt.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:80: recipe for target 'slack.o' failed
make: *** [slack.o] Error 1

Any idea/tip?

**Comment by EionRobb** [comment]
You'll need the -dev packages of everything, eg libpurple-dev

**Comment by minibiti** [comment]
Looks like this helped a lot indeed!
$ sudo apt install pidgin-dev
Then I had to use sudo to compile:
$ sudo make install

Thanks!

**Comment by dylex** [comment]
You should also be able to `make install-user` without sudo if you prefer.

**Comment by minibiti** [comment]
You need the sudo to write to these folders:
install -d /usr/lib/purple-2 /usr/share/pixmaps/pidgin/protocols/{16,22,48}
install libslack.so /usr/lib/purple-2/libslack.so
install -m 0644 img/slack16.png /usr/share/pixmaps/pidgin/protocols/16/slack.png
install -m 0644 img/slack22.png /usr/share/pixmaps/pidgin/protocols/22/slack.png
install -m 0644 img/slack48.png /usr/share/pixmaps/pidgin/protocols/48/slack.png

**Comment by dylex** [comment]
Yes, but `install-user` doesn't do that.
