### ISSUE TITLE
/me command doesn't work as expected

### ISSUE THREAD

**Issue by fredcooke** [dylex/slack-libpurple#64]
In the XMPP gateway with standard XMPP plugin things like "/me is going to bed" worked fine, but with this plugin you type:

/me vomits

and get

(10:37:49) channel_not_found

FWIW this works in slack web client just fine.

**Comment by dylex** [comment]
It looks like this is broken only for IMs, not for channels. I'll try some things, but this feature uses an undocumented slack API so it's not clear how it's supposed to work (or whether it's even possible).

**Comment by dylex** [comment]
Looks like just switching to the IM ID rather than the user ID fixed it.

**Comment by fredcooke** [comment]
Thanks! Super quick turn around :-)

**Comment by fredcooke** [comment]
Just updated and tested and although it works, the /me commands have massive lag and normal messages have no lag at all. The /me ones show up in the chat out of order with stuff sent after it and maybe 5 to 15 seconds delayed from hitting enter. Open a new ticket about the lag or stick with this and reopen to track related discussion?

**Comment by dylex** [comment]
I'm just using the libpurple2 built-in fetch url http client, which doesn't support http/1.1 persistent connections.  I believe libpurple3 has a better http client, so I'm opting to wait for that rather that implementing a new glib-compatible http client.  I would suggest looking through the slack and libpurple apis if you want to understand the constraints.
