### ISSUE TITLE
Can't join private channel

### ISSUE THREAD

**Issue by ehershey** [dylex/slack-libpurple#69]
Getting this error when I /join from irssi: 

purple - Error: Invalid Channel - Could not join channel - name_taken

**Comment by ehershey** [comment]
Thanks! If I add the channel without the leading "#" it works!

**Comment by dylex** [comment]
I haven't been able to find a slack API to do a more reasonable lookup/normalization, so in the mean time, I've just made it ignore any leading `#`.

**Comment by ehershey** [comment]
Could you just lookup the given channel without a #? 
Or check a known list of channels the user is already a member of? 

The current fix seems good enough to me.

**Comment by dylex** [comment]
Yeah, it's essentially doing those things, but the thing that's missing is there's no way to join/lookup a private channel by un-normalized name in the slack-api, only public channels.  Short of that, this may be the best we can do for now.
