### ISSUE TITLE
DM's from people not (yet) in my byddylist doesn't show up

### ISSUE THREAD

**Issue by kendrak24** [dylex/slack-libpurple#73]
As the title says, when I get an DM from someone not yet in my buddylist, the DM doesn't show up. If I open up slack in a web browser, and respond to the DM there, the conversation (and other person) then shows up in Pidgin.

**Comment by dylex** [comment]
Dup #22. I was hoping this was fixed, but it's been difficult to reproduce. If you could get a debug log of this happening it'd be really helpful.
