### ISSUE TITLE
First SegFault from Pidgin in 10 Years :-D

### ISSUE THREAD

**Issue by fredcooke** [dylex/slack-libpurple#74]
Can't quite pin it on this plugin, but... :-)

What I was doing was after driving to work, I had manage accounts open, and was doing my usual force off/on by unchecking each active box and then rechecking, and I fumbled the mouse and rechecked one straight away, then clicked one more, then it went down. Ie, felt like some sort of state vs concurrency issue to me.

What I usually do is uncheck each from top to bottom (currently 6) and recheck again from top to bottom to allow some time to die properly (in case it's needed). That's worked every Monday and Friday for some time. 

I'm not up to date with master and only have a few days left on this machine, however my other machine is the same and I'll do my best to help. The version I am running is tagged as FRED-0.2 in my fork, and is just after you added the ping behaviour. However you're not too far ahead, so there's probably still value in understanding the fault in this version in case it's harder to reproduce in later ones.

To debug I guess I have to do something like this:

- Install pidgin debug symbols
- Build plugin with debug enabled
- Execute in gdb
- Force issue (or try to!)
- Extract data from gdb with ? commands

Can probably figure most of that out by myself, but any help welcome.

**Comment by EionRobb** [comment]
https://developer.pidgin.im/wiki/GetABacktrace should help

**Comment by dylex** [comment]
This actually turns out to be fairly easy to reproduce. If you just disconnect before the first response comes back, it crashes once the response does come back.  I had assumed that passing an account to `purple_util_fetch_url` would cancel the request if the account were disconnected, but it doesn't seem to. I guess I should add an additional layer of checking, but since the account pointer itself is invalid at this point, this will take some thought.

**Comment by dylex** [comment]
If this is the same issue you were seeing (or a variant thereof), should now be fixed. All outstanding fetch requests are now explicitly cancelled on disconnect.

**Comment by fredcooke** [comment]
Dylan, you're a star! Once my finances are in order, I'm sending you a little beer/wine/whisky money.

Eion, thanks for the docs!
