### ISSUE TITLE
direct messages from bots (e.g. slackbot) don't propogate through to slack-libpurple clients

### ISSUE THREAD

**Issue by tychoish** [dylex/slack-libpurple#75]
We have a number of bots/apps in our slack environment that send notifications via a direct message to users. These show up in the "slackbot" window in the slack application, but do not propagate through to slack-libpurple.

Messages from these users work fine when sent to a channel, so I suspect there's something about the slackbot messages/windows that shows up differently in the API.

**Comment by dylex** [comment]
You mean they show up in the slackbot direct message window, but actually come from a bot user other than slackbot? Do messages from slackbot itself show up correctly there? Is this related to #29? Do you happen to know how the bots are sending the messages? I would expect a direct message to show up in a new DM IM window specific to each bot, but clearly the prpl is not handling bot users quite right, yet.

**Comment by tychoish** [comment]
I don't have this setup at the moment, and I think this is beyond stale 😬
