### ISSUE TITLE
Add support for message threads

### ISSUE THREAD

**Issue by exarkun** [dylex/slack-libpurple#76]
This is a feature request.

Slack has the notion of threads of messages.  A message in a channel can be replied to in a way that creates a new thread.  More messages can be added to this thread.  These messages can appear in the channel of the original message or not (controlled by a checkbox in the Slack web ui).

Make slack-libpurple able to interact with these message threads: to see the threads to which received messages belong and to be able to send messages to a given thread.

**Comment by dylex** [comment]
Do you have any thoughts for how this would work in the interface (be exposed to the user), given the constraints of what libpurple allows? The only thought I had was to expose threads as an entirely separate channel, but this may actually be more annoying or confusing than the current way of just flattening them all together.

**Comment by exarkun** [comment]
I don't, sorry. :/  I don't know libpurple at all, nor what constraints are imposed by its interface.  I just hoped it would be feasible to offer this functionality.

**Comment by FredCookeTHL** [comment]
I do, just pop an ID in a message FROM a thread (currently show up inline like they're normal) and provide a way of sending to that ID with a / command. OR, open a new tab/window (more like what slack does and likely easier and cleaner to use and implement) with the original message as context, and any subsequent messages that form the thread beneath. Was going to jump on here and request at least visibility of the fact that those messages are threaded as then you can open a web UI to respond to them without looking like a retard who hasn't realised you're supposed to reply in them :-)

**Comment by fredcooke** [comment]
I do, just pop an ID in a message FROM a thread (currently show up inline like they're normal) and provide a way of sending to that ID with a / command. OR, open a new tab/window (more like what slack does and likely easier and cleaner to use and implement) with the original message as context, and any subsequent messages that form the thread beneath. Was going to jump on here and request at least visibility of the fact that those messages are threaded as then you can open a web UI to respond to them without looking like a retard who hasn't realised you're supposed to reply in them :-)

**Comment by vn971** [comment]
@dylex if we just add a notion of message belonging to a thread, it'll be a big improvement already. Currently, there's no way to tell if a message is a thread reply or a new one.

Thoughts? I think that should be fairly easy..

**Comment by fredcooke** [comment]
Agreed, if there was some way to ID which message it came from, maybe by
original date stamp, that'd be even better. Another potentially annoying
option that I would like would be a new tab for each thread you're
following/involved in, then they're separate and there's no need to
identify as it'd be natural and would also let you reply, which the
in-channel option does not. Thoughts?

**Comment by vn971** [comment]
@fredcooke I like it! Especially if it's a doable task to implement!

**Comment by dylex** [comment]
It should be fairly easy just to add some kind of annotation for threaded messages with the timestamp of the original message. I'm happy to do this if it's helpful. It wouldn't give you any way to respond on the thread, though.

Treating threads as separate chats seems much harder, or at least I don't see any easy way to do it, but happy to accept thoughts or a PR.

**Comment by vn971** [comment]
@dylex if you'll have some experimental code and would need testers, feel free to ping, I'll test. (Arch user here, convenient with compiling.)

**Comment by vn971** [comment]
Re: 2a9aacf  -- nice!!

I think it's a good start! Most importantly, you already know if a reply was threaded or now.

I wonder on one technical side: if people reply to _you_, would you get a [more verbose] notification? If not, would adding the name of the parent comment-s author help? Like if Alice gets a reply from Bob, the message could be like `<Alice 09:15:31> hello, this is a message from Bob`.

Other ideas for message format:
```
Re: Alice 09:15:31: hello
Alice 09:15:31 ↪  hello
Alice 09:15:31 ⤷  hello
Alice 09:15:31 ↦ hello
Alice 09:15:31 
Alice 09:15:31 
Alice 09:15:31 
Re 09:15:31 ⇘ hello
```

Just some proposals to consider, in case something feels nice!
I personally find the "⤷" variation visually appealing. Don't know how common this unicode symbol is though...

**Comment by vn971** [comment]
UPD: updated comment ^

**Comment by vn971** [comment]
UPD: edited message format proposals once again, and made a simple PR with `⤷` character: https://github.com/dylex/slack-libpurple/pull/90

**Comment by kacf** [comment]
Take a look at https://github.com/dylex/slack-libpurple/pull/118 as well, which gives more complete thread support. There are several things that needs some discussing there.

**Comment by dylex** [comment]
With #118 merged I'm going to close this. We can keep adding specific features as requested.
