### ISSUE TITLE
Image download links stopped coming through a few days ago

### ISSUE THREAD

**Issue by fredcooke** [dylex/slack-libpurple#77]
Just comments now. Change to the API and behaviour? Or has my long-running pidgin instance got into a bad state? Only have one instance now so nothing to compare against. May change that in the near future, though.

**Comment by fredcooke** [comment]
Just updated to 6bf292ca0742443182fcf50249b1ff477662ecb7 and still no image links coming through :-( 

Edits still come through fine. Link enrichment still comes through fine as an edit. Must have changed the behaviour. I'd very much like to see these links! Especially because even though the files become unreachable via slack's UIs, you can still download them forever AFAICT.

**Comment by fredcooke** [comment]
By image links, I mean file links in general, not just images. Apologies.

**Comment by dylex** [comment]
This may be related to https://api.slack.com/changelog/2018-05-file-threads-soon-tread although I've seen file links as recently as Jul 25. If they have indeed moved file links out of the message, there will need to be additional processing to display them. Examples of the new message structure or PRs welcome.

**Comment by ehershey** [comment]
I noticed this too. It's extra frustrating because I don't even see that an image is there to be viewed, let alone see a link to download it.

Here's debug logging of an incoming image that I didn't see via bitlbee.

```
DEBUG slack: RTM 1: {"type":"presence_change","presence":"active","user":"UREDACTED"}
DEBUG slack: setting user redactedfname.redactedlname presence to active
DEBUG blist: Updating buddy status for redactedfname.redactedlname (Slack)
DEBUG websocket: message 81 len 260
DEBUG slack: RTM 1: {"type":"message","user":"UREDACTED","text":"before I begin, do any of these actually need to be disabled:","client_msg_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","team":"TREDACTED","channel":"GREDACTED","event_ts":"1532962821.000254","ts":"1532962821.000254"}
DEBUG websocket: message 81 len 2031
DEBUG slack: RTM 1: {"type":"message","text":"","files":[{"id":"FREDACTED","created":1532962825,"timestamp":1532962825,"name":"Screenshot 2018-07-30.png","title":"Screenshot 2018-07-30.png","mimetype":"image\/png","filetype":"png","pretty_type":"PNG","user":"UREDACTED","editable":false,"size":112199,"mode":"hosted","is_external":false,"external_type":"","is_public":false,"public_url_shared":false,"display_as_bot":false,"username":"","url_private":"https:\/\/files.slack.com\/files-pri\/TREDACTED-FREDACTED\/Screenshot_2018-07-30.png","url_private_download":"https:\/\/files.slack.com\/files-pri\/TREDACTED-FREDACTED\/download\/Screenshot_2018-07-30.png","thumb_64":"https:\/\/files.slack.com\/files-tmb\/TREDACTED-FBYQA5XBK-76aa409b54\/Screenshot_2018-07-30_64.png","thumb_80":"https:\/\/files.slack.com\/files-tmb\/TREDACTED-FREDACTED-76aa409b54\/Screenshot_2018-07-30_80.png","thumb_360":"https:\/\/files.slack.com\/files-tmb\/TREDACTED-FREDACTED-76aa409b54\/Screenshot_2018-07-30_360.png","thumb_360_w":323,"thumb_360_h":360,"thumb_480":"https:\/\/files.slack.com\/files-tmb\/TREDACTED-FREDACTED-76aa409b54\/Screenshot_2018-07-30_480.png","thumb_480_w":430,"thumb_480_h":480,"thumb_160":"https:\/\/files.slack.com\/files-tmb\/TREDACTED-FREDACTED-76aa409b54\/Screenshot_2018-07-30_160.png","image_exif_rotation":1,"original_w":512,"original_h":571,"permalink":"https:\/\/mongodb.slack.com\/files\/UREDACTED\/FREDACTED\/Screenshot_2018-07-30.png","permalink_public":"https:\/\/slack-files.com\/TREDACTED-FREDACTED-d671a7f671"}],"upload":true,"user":"UREDACTED","display_as_bot":false,"team":"TREDACTED","source_team":"TREDACTED","user_team":"TREDACTED","user_profile":{"avatar_hash":"e952a0c4acce","image_72":"https:\/\/avatars.slack-edge.com\/2017-01-03\/999999999999_deadbeefdeadbeefc14d_72.png","first_name":"John","real_name":"John Smith","display_name":"jsmith","team":"TREDACTED","name":"jsmith","is_restricted":false,"is_ultra_restricted":false},"channel":"GREDACTED","event_ts":"1532962827.000679","ts":"1532962827.000679"}
DEBUG slack: Ignoring unparsed message
DEBUG websocket: message 81 len 63
DEBUG slack: RTM 1: {"type":"presence_change","presence":"away","user":"UREDACTED"}
DEBUG slack: setting user cailin presence to away
DEBUG blist: Updating buddy status for cailin (Slack)
DEBUG websocket: message 81 len 148
```

**Comment by dylex** [comment]
Ah, that's quite helpful. I think we're looking at an optional array of https://api.slack.com/types/file per message. How should we display these? Something like: `<a href="$url_private">$title</a>`? Or is `$permalink` a better url?  Any other fields or formatting?

**Comment by fredcooke** [comment]
Thank you @ehershey !!! Hmmm. One of the links opens the slack UI and the other the file itself, right? Not sure what I'd prefer. What I typically do is open the slack UI (Because that's the link I had) and then click the image to open it, which opened a new tab, and then view and save it, for the record. I think putting both would probably be ugly and although I probably prefer the raw file link, what about comments on the image? Do those just come through naturally ah la threads? Probably safest to put the slack UI spec link.

**Comment by dylex** [comment]
Well, I've added a really basic and untested display for files.  We can iterate from there.

As for comments, it seems like they've gotten rid of them and replace them with threads, which have their own issues. They may just come through on the channel as usual, unmarked.

**Comment by fredcooke** [comment]
Thank you @dylex ! :-)

    (03/08/18 18:29:54) bob.jones: 
    ▎ Pasted image at 2018-08-03, 6:29 PM

Name redacted. Tested the link and instead of opening the image it opens the entire chat platform and takes 10 seconds to redirect and load everything, so it must be the other link that I (at least) want that opens just the image and the comment with it. Unless they changed it entirely, which would be sad. I'll try to patch it myself given the discussion above and see how it goes.

I thought one link would be the raw file to just view and the other the same as before, but it seems one must be the slack full chat UI with image in side bar on right, small. And the other what I had before with XMPP. Will post my results.

**Comment by fredcooke** [comment]
Even better, the url_private value goes direct to the image NOT in the slack UI which is what I want anyway, if you agree that that's better (perfect for a plugin or log tail script to cache credentials and download for the user, for eg) then please merge my PR (yet to be created). Cheers! :-) If not, maybe format like this:

    Pasted image at 2018-08-03, 6:29 PM (file link) (slack web app link)

Or similar?

**Comment by dylex** [comment]
Images seem to show up again. Closing.

**Comment by fredcooke** [comment]
Thanks again! :-)
