### ISSUE TITLE
Member list missing from a public "channel" turned private

### ISSUE THREAD

**Issue by anrxc** [dylex/slack-libpurple#86]
Hello. Thank you for this plugin. 

Recently I had to join a company "server" (I hope that's the terminology). Meaning it had a set of preexisting "channels", some private some public.  Every public and private channel except one showed the members list in the side panel fine except one, and nothing I tried helped to load the members list. 

More details: I am using a build of the last commit in master branch. This channel is a private channel and using web UI or using official client it permits me to see the member list. Interestingly typing "/who" in Pidgin prints out the member list in the chat window, just won't load it into the side panel.

Then I discovered this debugging output comparing two private channels, one of which loads the member list and one which does not, this helped the owner remember this tidbit of information: "this channel was created as a public one, and only later switched to private mode while the other [good] one was created as private from the start". Presumably these creations are done from the web UI client by clicking on that plus button, simplest method possible: 

Missing members:
`(18:53:39) slack: api response: {"ok":true,"channel":{"id":"ID HERE","name":"NAME HERE","is_channel":true,"is_group":false,"is_im":false,"created":TIMEHERE,"is_archived":false,"is_general":false,"unlinked":0,"name_normalized":"NAME HERE","is_shared":false,"parent_conversation":null,"creator":"CREATOR HERE","is_ext_shared":false,"is_org_shared":false,"shared_team_ids":["TEAM ID HERE"],"pending_shared":[],"is_pending_ext_shared":false,"is_member":true,"is_private":true,"is_mpim":false,"last_read":"TIME HERE","is_open":true,"topic":{"value":"","creator":"","last_set":0},"purpose":{"value":"","creator":"","last_set":0}}}`

Showing members:
`(18:57:42) slack: api response: {"ok":true,"group":{"id":"ID2 HERE","name":"NAME2 HERE","is_group":true,"created":TIMEHERE,"creator":"CREATOR HERE","is_archived":false,"name_normalized":"NAME2 HERE","is_mpim":false,"is_open":true,"last_read":"TIME HERE","latest":{"type":"message","user":"UID HERE","text":"blah blah blah","ts":"TIME HERE"},"unread_count":0,"unread_count_display":0,"members":["MEMBER1 ID","MEMBER2 ID"],"topic":{"value":"","creator":"","last_set":0},"purpose":{"value":"","creator":"","last_set":0}}}`

Knowing the API well you will probably know the exact difference between is_group and is_channel. Even though the owner is sure he created both the same way (with exception of switching Private mode on later for one of them), maybe that is not entirely accurate recollection after all. 

Maybe these is_channel types of private chats are still supposed to load their member list and this report will be interesting to you, but if they were never supposed to load the member list then feel free to close this report.  

We destroyed this chat and recreated it as private from the start and that helped me to load the member list, but there could be more chats in the future that get toggled to Private which will cause me the same problem.

Thanks.

**Comment by frh** [comment]
I also have this issue. I tried leaving and rejoining the channel to no avail.
