### ISSUE TITLE
URLs not shown in  channel messages

### ISSUE THREAD

**Issue by fbatogo** [dylex/slack-libpurple#88]
First, thanks for developing this extension!  It, along with many others, have helped me avoid having my CPU spend 90% of its time running IM apps!

Recently, I started to try to use a notifier in Jenkins to send me build status messages via Slack.  I followed the instructions carefully, and quickly had messages coming across.   However, I noticed that any place in the message that contained a URL was missing.   I installed the full Slack client on my machine, and found that the URLs show up properly there.   So, I believe this is an issue with slack-libpurple, and not with the Jenkins notifier plugin.

I threw together a simple "test" job in Jenkins so I could quickly and easily reproduce the problem, then sent a status message to a private channel using the Jenkins system, and had the debug log running when it came in.   This is the result : (With IP addresses and other "sensitive" information redacted, and spacing added for readability.)

---- Debug log data start ----

(10:18:19) slack: Unhandled RTM type dnd_updated_user

(10:18:27) websocket: message 81 len 707

(10:18:27) slack: RTM 1: {"text":"","bot_id":"(redacted)","attachments":[{"fallback":"The build was a success.  \n\tBuild URL : (<http:\/\/(redacted):8080\/job\/test\/28\/|Open>)  Other URL : <http:\/\/www.slashdot.com>\n\tTest data : Test Status:\n  No tests appear to have run!","id":1,"color":"bbaadd","fields":[{"title":"","value":"The build was a success.  \n\tBuild URL : (<http:\/\/(redacted):8080\/job\/test\/28\/|Open>)  Other URL : <http:\/\/www.slashdot.com>\n\tTest data : Test Status:\n  No tests appear to have run!","short":false}],"mrkdwn_in":["pretext","text","fields"]}],"type":"message","subtype":"bot_message","team":"T06LSDDHS","channel":"GEPLQ41ED","event_ts":"1544721507.003000","ts":"1544721507.003000"}

(10:18:27) pidgin-libnotify: Chat () (<br /><font color="bbaadd">▎ </font><b></b>: <i>The build was a success.  
	Build URL : (<http://(redacted):8080/job/test/28/|Open>)  Other URL : <http://www.slashdot.com>
	Test data : Test Status:
  No tests appear to have run!</i>)

---- Debug log data end ----

The debug output above seems to indicate that the URLs were received by Pidgin, but what I actually see in the chat window is this : 

---- Chat window output start ----

(10:18:27 AM) 
▎ : The build was a success.  
	Build URL : ()  Other URL : 
	Test data : Test Status:
  No tests appear to have run!

---- Chat window output end ----

So, it appears that while slack-libpurple is processing the Slack message, something is happening that strips out the URL.

A couple of potentially useful additional bits of information.

1. According to what I was able to find from Slack, formatting a URL in this way : 
`<http://(redacted):8080/job/test/28/|Open>`

Should cause the text "Open" to be displayed in Pidgin, and that text should link to the URL provided before the |.

2. For the 2nd URL in the message, the Jenkins plugin is configured to send that as text without the <> around it.   However, the <> end up on there somewhere along the way.   I don't know if the Jenkins plugin adds it, or if Slack sees that it is a URL and helpfully adds it.   I also don't know if this has any impact on a solution to the problem.  (Just wanted to include the info in case it is useful.)

Please let me know if there is any additional information I can provide.

Thanks!

**Comment by fbatogo** [comment]
I decided to take a few minutes and attempt to fix this issue myself.   I have a patch in my branch that seems to solve it.   Basically, to resolve it, when processing fields in an attachment, I ran the fields through slack_message_to_html(), which caused the URLs to show up as I would expect.

I'll be submitting a pull request shortly.

**Comment by dylex** [comment]
Thanks for the great analysis and quick fix.
