### ISSUE TITLE
Can't create more than one slack account in pidgin

### ISSUE THREAD

**Issue by serj-p** [dylex/slack-libpurple#9]
there is an issue with the current implementation
when I add second(different) slack account to pidgin it connects, but all contacts from the first account are doubled and none from the second are displayed

**Comment by dylex** [comment]
Is this for a different account on the same slack, or on a completely different slack.  I have accounts connected on two different slacks, which seems to work okay (though it does use the team name as the group name so I guess these should be different, too). I haven't tested two different account on the same slack. I'm also using explicitly different servers (`firstteam.slack.com` and `otherteam.slack.com`), which pidgin might need to make the accounts different...

**Comment by dylex** [comment]
That is true. I take it this now works with the correct tokens? I'm not sure how to check for this in libpurple but will look into it.

**Comment by serj-p** [comment]
yes now it works pretty well. there are issues with displaying complexly formatted messages(they are just not shown), I'll try to find  an accurate way to reproduce and open a separate ticket.

**Comment by dylex** [comment]
That's probably the same as #7. We mainly need to figure out formating to address that.
