### ISSUE TITLE
Maintaining online presence?

### ISSUE THREAD

**Issue by zer0def** [dylex/slack-libpurple#91]
Would it be much of a bother to implement something like https://libraries.io/rubygems/slack-keep-presence/0.1.9 in order to prevent Slack from marking a currently logged in Purple session as away, unless explicitly set?

**Comment by dylex** [comment]
I'd be happy to do such a thing if we knew how. #87 made some changes in how away/active handling was done for the new slack api, but still doesn't seem to fix this and it doesn't seem to be documented. The package you link to seems to have disappeared, and based on the date, I suspect does the same thing that we used to, which no longer works.

**Comment by zer0def** [comment]
Contents of the entire app are in one Ruby file, after unpacking the gem: https://dpaste.de/iUUx

**Comment by dylex** [comment]
Yes, that looks like the same call we make, except with an added set_active flag which the docs claim is no longer functional as of May 2018. In particular, the docs say "There's no way to force a user status to active," but they don't explain how "The Slack message servers will automatically detect activity in the client" so there must still be something the real clients do.  Does the ruby still actually work?

**Comment by zer0def** [comment]
Just double-checked both slack-libpurple and slack-keep-presence, the latter maintains presence correctly, while -libpurple is switched to away after 30 minutes and stays there.

**Comment by zer0def** [comment]
Updating script contents, given that my previous paste has expired: https://ptpb.pw/AHFVN7Y0DTvZKgwrH0knayq-ZuqS.rb

**Comment by zer0def** [comment]
Ok, so I've spent some time combing through the ruby thing and noticed:
- it looks for the Slack user id of the account it's holding whenever an `presence_change` event arrives and runs it's routine, so unless `slack_presence_change()` calls `slack_set_status()` somehow (I have no awareness of Purple's internals at this time), the account will eventually get marked away after the 30 minute period, anyway, especially if you have a longer away timer
- haven't you confused the `users.setActive` API method with the `set_active` flag that's never mentioned in `users.setPresence`'s documentation, yet used in the script?

**Comment by zer0def** [comment]
Turns out I was wrong by claiming `set_active` as the reason the Ruby script worked and since it immediately reconnects the RTM socket after trying that flag, I've jammed in a forced reconnect myself [here](https://github.com/zer0def/slack-libpurple/commit/5778af5bdbc9891be2dff727489b5c0a3a083b27), so if it remains stable for in the coming days/weeks, I'll be sure to make a PR and/or reimplement this in a more proper place.
